# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20171209_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
