# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20171212_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_locked',
            field=models.BooleanField(default=False, help_text="Used by bank employee for lock user's account.", verbose_name='locked'),
        ),
    ]
