# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-26 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=50)),
                ('exchange_rate', models.FloatField(help_text='Exchange rate against the BYN')),
            ],
            options={
                'verbose_name_plural': 'currencies',
            },
        ),
    ]
