# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-26 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='exchange_rate',
        ),
        migrations.AddField(
            model_name='currency',
            name='purchase_rate',
            field=models.FloatField(default=1, help_text='against the BYN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currency',
            name='sale_rate',
            field=models.FloatField(default=2, help_text='against the BYN'),
            preserve_default=False,
        ),
    ]
