# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 07:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_auto_20171126_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='purchase',
            field=models.FloatField(help_text='against the BYN', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='sale',
            field=models.FloatField(help_text='against the BYN', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
