# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0003_auto_20171126_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externaltransfer',
            old_name='is_favourite',
            new_name='is_favorite',
        ),
    ]
