# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-26 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20171124_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipient', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='id',
        ),
        migrations.RemoveField(
            model_name='bankcard',
            name='id',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='number',
            field=models.CharField(max_length=63, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='number',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='externalcharge',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.BankCard'),
        ),
        migrations.AddField(
            model_name='cardcharge',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.BankCard'),
        ),
        migrations.AddField(
            model_name='cardcharge',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.BankCard'),
        ),
    ]
