# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-26 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20171126_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardcharge',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_charges', to='members.BankCard'),
        ),
        migrations.AlterField(
            model_name='cardcharge',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_charges', to='members.BankCard'),
        ),
        migrations.AlterField(
            model_name='externalcharge',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_charges', to='members.BankCard'),
        ),
    ]
