# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-26 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20171126_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='members.BankCard')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='members.BankCard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipient', models.CharField(max_length=30)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_transfers', to='members.BankCard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='cardcharge',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='cardcharge',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='externalcharge',
            name='sender',
        ),
        migrations.DeleteModel(
            name='CardCharge',
        ),
        migrations.DeleteModel(
            name='ExternalCharge',
        ),
    ]
