# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-26 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20171126_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currencies.Currency'),
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
